// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currenatPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNyP4rzGavy3gvzZ1SFd9KjQUElMNbgGQ',
    appId: '1:72604447683:web:8d450cb5b4a5e3ab6a4376',
    messagingSenderId: '72604447683',
    projectId: 'pihuplus-ca67d',
    authDomain: 'pihuplus-ca67d.firebaseapp.com',
    storageBucket: 'pihuplus-ca67d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1K29JtnPfHr5fBuJExRHVxghaCXW0-Zw',
    appId: '1:72604447683:android:3f57268810ca52ff6a4376',
    messagingSenderId: '72604447683',
    projectId: 'pihuplus-ca67d',
    storageBucket: 'pihuplus-ca67d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs2LvJJY3-eN-G8f-IeCoBjMsH6wudsVE',
    appId: '1:72604447683:ios:5df61488683dfb676a4376',
    messagingSenderId: '72604447683',
    projectId: 'pihuplus-ca67d',
    storageBucket: 'pihuplus-ca67d.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs2LvJJY3-eN-G8f-IeCoBjMsH6wudsVE',
    appId: '1:72604447683:ios:5df61488683dfb676a4376',
    messagingSenderId: '72604447683',
    projectId: 'pihuplus-ca67d',
    storageBucket: 'pihuplus-ca67d.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNyP4rzGavy3gvzZ1SFd9KjQUElMNbgGQ',
    appId: '1:72604447683:web:ef43baf132908ded6a4376',
    messagingSenderId: '72604447683',
    projectId: 'pihuplus-ca67d',
    authDomain: 'pihuplus-ca67d.firebaseapp.com',
    storageBucket: 'pihuplus-ca67d.firebasestorage.app',
  );
}
